### ISSUE TITLE
Tobira Integration

### ISSUE THREAD

**Issue by JulianKniephoff** [opencast/opencast-admin-interface#311]
https://github.com/opencast/opencast/pull/4131 added Tobira integration to the old admin UI. This should be forward-ported.

There might also be some future requirements that can be tracked here.

See also:

* https://github.com/elan-ev/tobira/issues/718
* https://github.com/elan-ev/tobira/issues/719

**Comment by dagraf** [comment]
Some additional requirements:

- The Tobira tab should also be there for events (in 'Event details'). In order to get the direct link to the video page and to which pages in Tobira do contain this video.
- It should not only be possible to add series to Tobira when they are created, but also afterwards (i.e. when they have already been created).
- Optimize solution to (de)select a sub-page during the creation of a series. Suggestion: To select the desired subpage, a check mark must be placed in the desired column.
Add wording: "A direct link will be available."
- Optimize solution if a new sub-page is to be created.
Suggestion:: When a new sub-page is created, I cannot confirm the creation but only undo it (via the red "x", see screenshot). I would suggest offering a green "checkmark" next to the red "x". This is only displayed once I have filled in the mandatory fields. Clicking on it means that the title and path to the sub-page can no longer be edited (but are displayed identically to the other sub-pages).
<img width="611" alt="Bildschirmfoto 2024-04-03 um 15 47 57" src="https://github.com/opencast/opencast-admin-interface/assets/15246287/12554784-80eb-4c1d-9562-2aaed455869d">

**Comment by oas777** [comment]
On David's suggestions:

- +1. But what do you mean by "to which pages in Tobira do contain this video."
- Do you mean selecting a new "target page" i. e. path for publication? If so, I agree and would add that this should also be available for events and include edit the name of path segments (if you're allowed to), for example for correcting an earlier input. 
- Isn't is possible already to select 
![image](https://github.com/opencast/opencast-admin-interface/assets/1752342/ac182247-5d5c-4d8b-94d6-79dfc63338a6)
and de-select 
![image](https://github.com/opencast/opencast-admin-interface/assets/1752342/40b489bf-c705-43d3-bcc6-0a6dd3f4e817)
a subpage by clicking on it?
- Formally, the confirmation is in the last line 
![image](https://github.com/opencast/opencast-admin-interface/assets/1752342/849ba090-69b8-4243-965f-f736c6cf4695)
which you then confirm by clicking "Next". But your solution is way more intuitive.

**Comment by dagraf** [comment]
> * But what do you mean by "to which pages in Tobira do contain this video."

See screenshot: For series, there is not only shown the direct link to this series but also the "Pages in Tobira that contain this series". The same should be offered for videos".
<img width="622" alt="Bildschirmfoto 2024-05-21 um 09 16 18" src="https://github.com/opencast/opencast-admin-interface/assets/15246287/c62a33bc-610b-4b4b-aea3-99046c10c0d6">

**Comment by dagraf** [comment]
> > * But what do you mean by "to which pages in Tobira do contain this video."
> 
> See screenshot: For series, there is not only shown the direct link to this series but also the "Pages in Tobira that contain this series". The same should be offered for videos.
> <img alt="Bildschirmfoto 2024-05-21 um 09 16 18" width="622" src="https://private-user-images.githubusercontent.com/15246287/332321515-c62a33bc-610b-4b4b-aea3-99046c10c0d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzYyMjYsIm5iZiI6MTcxNjI3NTkyNiwicGF0aCI6Ii8xNTI0NjI4Ny8zMzIzMjE1MTUtYzYyYTMzYmMtNjEwYi00YjRiLWFlYTMtOTkwNDZjMTBjMGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3MTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNzQ3N2ViZWI5MjFhYjI0MGJmZDI2NWRhYzMwNjIxMTUyNWQ0YmFlOGRjNGRkNjA4MDJhY2Q5ZmMyNmE3YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gvnIaOC3SXfJsIvUCAL4a9mcyCUsEpuqAAYHYdEerYs">

> > * Isn't is possible already to select and de-select a subpage by clicking on its name in the first column (Subpage title)?
> 
> Yes, it is possible. That's why wrote "Optimize solution to (de)select a sub-page during the creation of a series".

**Comment by oas777** [comment]
A reminder to @JulianKniephoff to update David and myself about the status of this one. Also, I should mention this one is expected to solve https://gitlab.elan-ev.de/opencast/eth/tobira/-/issues/30 (change URL of publication ex post).

**Comment by JulianKniephoff** [comment]
We sent the offer and are still waiting for the order from Apereo. :/

**Comment by JulianKniephoff** [comment]
Since this seems to keep causing confusion in other communication channels I would like to clarify again that this issue was only about porting the Tobira integration that existed in the old admin UI to the new one. Hence it is solved by #313. This has nothing to do with the additional features requested by @dagraf.

Most, if not all, of these are addressed by #878 and the accompanying PRs for Tobira and Opencast. If it does **not** cover some requirement, and there isn't an issue for that, yet, we should create it and integrate it in our plan.

Some further issues/requirements already exist in the Tobira repository:

* https://github.com/elan-ev/tobira/issues/1176
* https://github.com/elan-ev/tobira/issues/719
* https://github.com/elan-ev/tobira/issues/718
* https://github.com/elan-ev/tobira/issues/364

/cc @oas777
