### ISSUE TITLE
Event details - access policy save and cancel buttons position is wrong

### ISSUE THREAD

**Issue by viwiebe** [opencast/opencast-admin-interface#604]
![oc_accesspolicy](https://github.com/opencast/opencast-admin-interface/assets/37619925/0710700b-2485-4d49-96ee-f50feaf0ee3a)

This also seems to be the case for other save/cancel buttons. Tested with Firefox and Chrome.

**Comment by Arnei** [comment]
Looks fine on the current `main`, in Chrome at least.
![Bildschirmfoto vom 2024-06-05 11-07-45](https://github.com/opencast/opencast-admin-interface/assets/14070005/b5947509-b134-45ef-b792-c7ce9337e083)

**Comment by kruemelm0nsta** [comment]
Event Details - Comments also wrong button position on Firefox at stable.opencast.org
![grafik](https://github.com/opencast/opencast-admin-interface/assets/131258682/a5aff7a7-c235-4d68-88fa-671b4907daaf)

**Comment by marwyg** [comment]
stable.opencast.org has an old version I think.
All the save buttons were (hopefully) fixed here: https://github.com/opencast/opencast-admin-interface/pull/572
The Comment section is a little bit special and was fixed here: https://github.com/opencast/opencast-admin-interface/pull/565

You can go to the very bottom of the PRs and use the link there to see if the buttons are correct now. If they look as you expect, please close this issue here.
